<?xml version="1.0"?>
<package format="3">
  <name>ur5_experiment</name>
  <version>0.1.0</version>
  <description>UR5e gripper workcell for MuJoCo vs Gazebo comparison</description>
  <maintainer email="you@example.com">charan</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ur_description</exec_depend>
  <exec_depend>ur_simulation_gazebo</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
